# Parametric spline to define race course

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate
%matplotlib inline 

## Homemade B-splines:

In [2]:
k = 3 # degree of spline
n = 4 # number of control points = n + 1
m = n + k + 1

P = np.array([[0,0,1,1,2],[0,1,1,0,0]])
T = np.array([[0,0,0,1.0/4,2.0/4,3.0/4,1,1,1]]).T
P[0]

array([0, 0, 1, 1, 2])

In [3]:
t = .68
N0 = np.array((t >= T[:-1]) * (t < T[1:]), dtype=int)
# N = np.concatenate((N,N),axis=1)
N0

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [4]:
invd1 = T[1:] - T[:-1]
invd2 = T[2:] - T[:-2]
invd3 = T[3:] - T[:-3]
# take care of empty knot spans
for i in range(invd1.shape[0]):
    if invd1[i] != 0:
        invd1[i] = 1.0/invd1[i]
        
for i in range(invd2.shape[0]):
    if invd2[i] != 0:
        invd2[i] = 1.0/invd2[i]
        
for i in range(invd3.shape[0]):
    if invd3[i] != 0:
        invd3[i] = 1.0/invd3[i]
        
# dists[:-1]+dists[1:]
print invd1
print invd2
print invd3

[[ 0.]
 [ 0.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 0.]
 [ 0.]]
[[ 0.]
 [ 4.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 4.]
 [ 0.]]
[[ 4.        ]
 [ 2.        ]
 [ 1.33333333]
 [ 1.33333333]
 [ 2.        ]
 [ 4.        ]]


In [5]:
p = 1
N1 = ((t-T[:-p])*invd1*N0)[:-1] + ((T[p:] - t)*invd1*N0)[1:]
N1

array([[ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.28],
       [ 0.72],
       [ 0.  ],
       [ 0.  ]])

In [6]:
p = 2
N2 = ((t-T[:-p])*invd2*N1)[:-1] + ((T[p:] - t)*N1*invd2)[1:]
N2

array([[ 0.    ],
       [ 0.    ],
       [ 0.0392],
       [ 0.7016],
       [ 0.2592],
       [ 0.    ]])

In [8]:
p = 3
N3 = ((t-T[:-p])*invd3*N2)[:-1] + ((T[p:] - t)*N2*invd3)[1:]
print N3

[[ 0.        ]
 [ 0.00365867]
 [ 0.33489067]
 [ 0.56813867]
 [ 0.093312  ]]


In [ ]:
tt = np.arange(0,1.0,.01)
rx = np.zeros(tt.shape)
ry = np.zeros(tt.shape)
for i in range(tt.shape[0]):
    rx[i] = np.dot(P[0],N3)
    ry[i] = np.dot(P[1],N3)

In [ ]:
plt.figure()
plt.hold=True
plt.scatter(P[0],P[1])
plt.plot(rx,ry)
# plt.axis([-0.05, 2.05, -0.05, 1.05])
plt.axis('equal')
plt.show()

In [ ]:
 
for j in range(k):
    if j == 0:
        for i in range(m - 1):
            if T[i] == T[i+1]:
                N[i] = 0
            elif T[i] <= t and T[i + 1] > t:
                N[i][0] = 1
    else:
        for i in range(n+1):
            if T[i + j] - T[i] > 0: 
                N[i][j] = ((t - T[i])/(T[i+j] - T[i])) * N[i][j-1] + ((T[i+j+1] - t)/(T[i+j+1] - T[i+1])) * N[i+1][j-1]

N